### ISSUE TITLE
No "sphere2/" folder in dataset

### ISSUE THREAD

**Issue by arxrean** [facebookresearch/sparsh#2]
Hi,

I would like to run the slip detection downstream task and used `./config/experiment/downstream_task/slip/digit_mae.yaml` as the config. The code tried loading "sphere2/batch_*" as the list_datasets but there is no "sphere2/" folder in the provided huggingface repo. Did I miss anything? Thanks.

**Comment by carolinahiguera** [comment]
Hi. Thanks for flagging the issue. Please download the dataset again from [hf](https://huggingface.co/datasets/facebook/digit-force-estimation). We have uploaded the missing dataset.
