### ISSUE TITLE
Test data for force estimation task

### ISSUE THREAD

**Issue by arxrean** [facebookresearch/sparsh#4]
Is there any reason to only use flat/batch_1 as the test set for the force estimation task instead of also including sharp/* and sphere/* data?

https://github.com/facebookresearch/sparsh/blob/main/config/task/t1_force_estimation.yaml

**Comment by carolinahiguera** [comment]
The reason is to test on an unseen shape. Please feel free to experiment doing evaluation on seen shapes during training, such as sharp and sphere data!

**Comment by arxrean** [comment]
Thanks for your reply. It looks like the model is trained with [flat/batch_2 data](https://github.com/facebookresearch/sparsh/blob/main/config/data/digit_force.yaml#L20). Do you mean flat/batch_1 and flat/batch_2 have different shapes?

**Comment by carolinahiguera** [comment]
You would need to remove the shape from the training list for which you want to test shape generalization. Or you can add all `batch_X` for all shapes in the training list and use `batch_Y` to eval the same shapes but different locations and force profiles.

**Comment by akashsharma02** [comment]
@arxrean If you're concerns are addressed, can we close this issue?

**Comment by arxrean** [comment]
Yes. Thank you.
